### ISSUE TITLE
modify time Label TextStyle 

### ISSUE THREAD

**Issue by mayouf** [suragch/audio_video_progress_bar#1]
Hi, 

First of all, thx for this plugin. I been trying several progress bar, they all had a non value exception that I did not debug.

Your plugin works like a charm.

I just need to modify the label time Style and color. My background color is dark, then I need to enlight the label color as they are not visible.

Would you please tell me how can I achieve this please ?

Maybe this would be a simple request to add too.

thx dude

**Comment by mayouf** [comment]
I found a solution:

I change my themeData in main.dart. 

I saw that you label style is based on what we specify on textTheme bodyText1. Then I just changed its value on `main.dart`.

```
theme: ThemeData(
                  primarySwatch: Colors.blue,
                  visualDensity: VisualDensity.adaptivePlatformDensity,
                  textTheme: TextTheme(
                    bodyText1: TextStyle(color: Colors.white),
                  ),
                )
```

But I think it would be a nice feature to set the label style.

thx again buddy

**Comment by suragch** [comment]
@mayouf, there is now a `timeLabelTextStyle` thanks to @hacker1024 

Regarding your total time label staying at 00:00, could you open a new issue for that? I didn't get that issue in the example app.

**Comment by suragch** [comment]
Changes have been published in version 0.3.1.

**Comment by mayouf** [comment]
Hi @suragch,

The label duration are still buggy.

Here below a link to a project to reproduce the bug. 

[click here - github of the exampleProgressBar](https://github.com/mayouf/exampleProgressBar.git)

This project is actually the example folder from this plugin: 

**[assets_audio_player: ^3.0.3+2](https://pub.dev/packages/assets_audio_player)**

I just took it and modify a screen to compare two progress Bar.

- So go to the folder 'Example'
- launch this specific file: 'lib/main_multiples.dart'
- You will see a screen with multiple audios having their own progressBar
- See at the line 210, a column gathering stacking both progress bar:

It compares two progress Bar:
- the Neuromorphic Slider from this plugin :
- your own progressBar in Orange color.

You check on the label Duration, you will immediztely notice the issue: they are stuck on the same duration everytime, which is here 01:24


<img src="https://user-images.githubusercontent.com/5865600/116107484-5deb7180-a6b3-11eb-8d8f-1ad5eb66e600.png" width="400">

Im running the project on Android 30 and 29.

**Comment by suragch** [comment]
@mayouf Can you create a new issue for this? This is a separate issue that has already been closed.

**Comment by suragch** [comment]
@mayouf Never mind. You don't need to create a new issue. The problem is in your code. You hard-coded the total time. https://github.com/mayouf/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_multiples.dart#L214

**Comment by mayouf** [comment]
Hi @suragch 

My bad, the hard coded duration was in fact to test wether the label would show up...and the answer is no...I have a strange bug...The label time do not show and remains at ZERO...even hard coded...

Im digging in it today...thanks for getting back
