### ISSUE TITLE
Padding issue

### ISSUE THREAD

**Issue by giga10** [suragch/audio_video_progress_bar#13]
Could you add some horizontal padding for the actual progress bar, when timeLabelLocation.sides is set? Or maybe exposing a new property for that?

![Screenshot_20210719-205321_3](https://user-images.githubusercontent.com/80179318/126217133-39f2ecc2-824d-496d-84b1-2ebdeb7dd23f.png)

```
ProgressBar(
   ...
   barHeight: 3,     
   thumbRadius: 8,
   thumbGlowRadius: 16,
   timeLabelLocation: TimeLabelLocation.sides,
);
```

**Comment by suragch** [comment]
That's a good point. It's too close. After observing another progress bar, I noticed that the left side of the thumb should only go to the left extent of the bar, and that the right side of the thumb should only go to the right side of the bar. Currently the center of the thumb goes to the left and the right. That makes it stick out too far (and be too close to the text.) Let me keep the text to the bar padding approximately the same for now but just fix the thumb location on the track.

**Comment by suragch** [comment]
I've published a new release where the thumb radius does not extend beyond the left or right of the progress bar extent. I used a hard-coded 10 pixel padding for `TimeLabelLocation.sides`. Let me know if this works for you.

<img width="302" alt="Screen Shot 2021-07-20 at 14 03 17" src="https://user-images.githubusercontent.com/10300220/126271045-7e0786f8-06f5-4d71-a51d-110fa58b1fa2.png">

**Comment by giga10** [comment]
Great job! This is what I was looking for. It looks much better now. Thank you.
