### ISSUE TITLE
Set padding between bar and label

### ISSUE THREAD

**Issue by sh1l0n** [suragch/audio_video_progress_bar#14]
As user I would want to manage the padding between the progress bar and the labels, could be possible with the current design?

**Comment by suragch** [comment]
It's not currently possible. Is the default padding not good for you?

**Comment by sh1l0n** [comment]
Not at all, I mean, the widget its really customizable, i love it. But the margin between the circular indicator and the text its really small, if you set a low font size (10,9,8...) the circular thumb seems that overlaps the text.

**Comment by sh1l0n** [comment]
Lines 621-624 of audio_video_progress_bar.dart

```
  final labelDy = (isLabelBelow) ? barHeight : 0.0;
    final leftLabelOffset = Offset(0, labelDy);
    final leftTimeLabel = _leftTimeLabel();
    leftTimeLabel.paint(canvas, leftLabelOffset);
```

Maybe the solution is to add a new parameter to  _RenderProgressBar constructor, maybe called labelPadding
```
 
  final labelDy = (isLabelBelow) ? max(barHeight, labelPadding)  : 0.0;
    final leftLabelOffset = Offset(0, labelDy);
    final leftTimeLabel = _leftTimeLabel();
    leftTimeLabel.paint(canvas, leftLabelOffset);
```

**Comment by suragch** [comment]
I added a `timeLabelPadding` parameter to the widget. (This matched the naming of the other `timeLabel...` parameters a little more than `labelPadding`.) 

Check it out and let me know if it works for you. Version 0.6.1.

**Comment by sh1l0n** [comment]
Works perfect for me, thanks a lot :)

**Comment by suragch** [comment]
Great! You're welcome
