### ISSUE TITLE
Progress thumb 'lag' on start and end 

### ISSUE THREAD

**Issue by giga10** [suragch/audio_video_progress_bar#15]
This is a direct consequence of the way you solved #13. I know what is the cause, but don't know how to explain it in English precisely. It is all about thumb's sides and center. On song (of few minutes duration), thumb starts to move too late (after few seconds) and it reaches the end too early (few seconds early), before the duration has been completed. Those seconds that are lost are due to the fact that sides of the thumb are reaching the start/end of progressbar, and NOT its center, as it should be.

I will try to record video about the issue, and share it here if you need it.

**Comment by suragch** [comment]
I understand the problem. What behavior would you like to see?

**Comment by suragch** [comment]
It might have been a mistake to make the edge of the thumb match the ends of the bar. I'm thinking about reverting it back.

The other option would be to make the thumb's point location move move proportionally across its diameter as it moves across the bar. The only drawback for this would be that it would look slightly off center when tapping at a location near the ends.

Here is an image that shows that. The red dots are the tap locations.

![tap](https://user-images.githubusercontent.com/10300220/127724917-2b4d3a27-e409-4d94-9b9e-daf6da3800f5.png)

**Comment by giga10** [comment]
Hm, I think that you should revert it back.  That before was the correct behavior. But how would that affect the timelabelPadding property? Will it still be there?

**Comment by suragch** [comment]
I agree with you. I'll keep the `timeLabelPadding` and maybe increase the default side label padding a little. In the original version the widget also included the thumb radius at the beginning and end in its intrinsic size calculation. I think I won't add that part back, though. That means the thumb would paint outside of the widget bounds when at the beginning and end (if the labels are above or below), but the thumb glow does that now anyway. People can wrap `ProgressBar` with a `Padding` widget if that produces an undesirable effect.

**Comment by giga10** [comment]
Yep. That sounds good to me. Looking forward to trying it.

**Comment by suragch** [comment]
I released this as 0.7.0. You can try it out.

**Comment by giga10** [comment]
I have just tried v0.7.0. It works flawlessly. Thank you for quick fix. Great support from your side.
