### ISSUE TITLE
Thumb and progress not updating when hooked to a VideoPlayerController

### ISSUE THREAD

**Issue by ervindobri** [suragch/audio_video_progress_bar#16]
Prerequisites:

- VidePlayerController 
- ProgressBar with VideoPlayerController as the source for the progress, and total values. (no buffering required)

Issue: Progress and thumb position should update according to position, but instead it only updates when a setState is called.

Widget:
```
ProgressBar(
        progress: localController.value.position,
        total: localController.value.duration,
        timeLabelLocation: TimeLabelLocation.none,
        onSeek: (duration) {
          print("Duration: $duration");
          setState(() {
            localController.seekTo(duration);
            // localController.play();
            elapsed =
                // localController.value.position +
                duration;
          });
          print(localController.value.position);
        },
      ),
```

**Comment by suragch** [comment]
I'm not sure it's the widgets responsibility to rebuild the UI when `onSeek` is called. I'd have to look into how some of the standard widgets handle this. I think it's a fine solution to call `setState` yourself. However, if there is a good argument for having the widget call `setState` internally, I'd be willing to listen to it.

**Comment by giga10** [comment]
Hm, this implementation is a bit odd for me. Shouldn't ProgressBar widget be wrapped with StreamBuilder or ValueListenableBuilder? Is this one wrapped?

**Comment by suragch** [comment]
When I was looking at the Flutter [Slider](https://api.flutter.dev/flutter/material/Slider-class.html) widget, the sample code uses `setState`, so this seems to be a valid solution. It also doesn't require updating the package, so I'm going to close this issue for now. Feel free to reopen or add a new issue.
