### ISSUE TITLE
Select start and end time

### ISSUE THREAD

**Issue by winterdl** [suragch/audio_video_progress_bar#18]
User could select point A then B, the widget draw line from A to B with different color.

**Comment by suragch** [comment]
You mean having the option where users can select the start time and end time?

That's an interesting idea. It would take a bit of work, though, so I'm not going to implement it now. I recommend you copy the source code to your project and implement the feature yourself. 

Let's keep this issue open and if other people have a need for it we can consider implementing it in the future. I'd like to see an animated gif or at least a screen shot of a working example from somewhere else.

**Comment by suragch** [comment]
Since this issue hasn't had any updates recently, I'll close it for now. Feel free to reopen or start a new issue. If you do, adding images and describing the use case more would help.
