### ISSUE TITLE
[Feature Request] remaining duration 

### ISSUE THREAD

**Issue by cedvdb** [suragch/audio_video_progress_bar#19]
Thanks for the package and the tests written, they are always appreciated.

It would be nice if there was an option to display the remaining duration. In other words, instead of displaying the current duration position and the total one, just the duration remaining would be displayed.  Such that if an audio is a 10 second clip, at the start it would display 00:10, then after 5 seconds 00:05, then after another 5 seconds 00:00 (only one duration displayed at a time).

Alternatively let the user decide how to display the duration, as other people may have other requirements (like displaying millis for example)

**Comment by suragch** [comment]
You can set the time label type like so:

```dart
timeLabelType: TimeLabelType.remainingTime,
```

**Comment by cedvdb** [comment]
The minus in front of the right label looks very weird. Also showing only the time remaining would be better. This is a suggestion, I might fork if needed.

**Comment by suragch** [comment]
You can fork for now for a quick (and maybe the best) solution. Another option would be to use the no label option and then add your own Text widget labels in the normal widget tree.

Alternatively, you could open a new feature request for something like TimeLabelType.remainingTimeNoDash. If there is sufficient interest from the community I'll add it.

**Comment by cedvdb** [comment]
The no label solution suits me
