### ISSUE TITLE
Position of the thumb when at the start and end of the bar

### ISSUE THREAD

**Issue by suragch** [suragch/audio_video_progress_bar#21]
Issues #13 and #15 affected where the thumb is drawn when at the start or end of the bar.

Currently the center of the thumb goes all the way to the ends of the bar. That means the thumb radius will draw outside of the widget area.

<img width="526" alt="Screen Shot 2021-08-11 at 12 12 54 PM" src="https://user-images.githubusercontent.com/10300220/128968678-980ad23e-b839-43e2-aedd-51c07ca79885.png">

However, between #13 and #15 the thumb radius was aligned with the bar like so:

<img width="520" alt="Screen Shot 2021-08-11 at 12 13 13 PM" src="https://user-images.githubusercontent.com/10300220/128968770-766411dd-fbf8-4d0f-9645-187a92ff6852.png">

I like that look because it lines up well with vertical labels. The disadvantage is that the thumb will not start moving until the current time passes the center of the thumb. Also it will stop moving one radius-width before the end of the song. Usually this is only a few seconds, though, and for me I don't mind that.

So I'm thinking of adding an option to select where the thumb will align. I'll keep centered as the default since that is what it is now, but are there good API naming suggestions?

Perhaps this:

```dart
thumbAlign: ThumbAlignment.edge,
```
```dart
enum ThumbAlignment {
  center,
  edge,
}
```

**Comment by giga10** [comment]
I really like the idea of having an option for this. For me personally, I prefer the current implementation, but some may not, so this is good observation. 

Regarding API naming, the one you suggested seems fine to me.

**Comment by suragch** [comment]
Version 0.9.0 adds this functionality. I adjusted the API, though.

```dart
this.thumbCanPaintOutsideBar = false,
```
