### ISSUE TITLE
Question: Progress bar support live videos?

### ISSUE THREAD

**Issue by kkoken** [suragch/audio_video_progress_bar#22]
Hi,

Thank you for an amazing tool. I was wondering progress bar support live videos?

**Comment by suragch** [comment]
If you take care of the live video part, the progress bar will work with it. You just need to supply the total video length and current play time as a Duration stream to the progress bar.

**Comment by suragch** [comment]
See also issue #26. If you are doing live video you might try setting the total time to the buffered time.
