### ISSUE TITLE
dragging works fine but just tapping progress bar does not move video position

### ISSUE THREAD

**Issue by Hwan-seok** [suragch/audio_video_progress_bar#23]
Is this a bug? or didn't implemented?

**Comment by suragch** [comment]
onSeek should be called when you tap the bar. After that you need to take the given duration and move the video position yourself.

**Comment by Hwan-seok** [comment]
Ah, I thought the tapping behavior does not work in every environment but it does not work in specific cases.
I found that progress bar tapping is not work in `PageView with itemCount >= 2` and the dragging works fine.

To make sure, `Drag` is calling onSeek, onDragStart & onDragEnd but `Tap` is not calling these.

**Comment by suragch** [comment]
It sounds like this may be related to which widget is getting the tap event. I'm not exactly sure how to fix that. If you add a regular button does it receive a tap event?

**Comment by Hwan-seok** [comment]
Other tap gesture does work.
Hmm... I can provide minimal [reproduction code](https://github.com/Hwan-seok/flutter-key-not-working) but this library is implemented really row level to me.. so I am not sure what made this wrong...

**Comment by suragch** [comment]
You have a GestureDetecter in your example. It may be stealing the tap event from the progress bar. Try removing it and seeing if the problem persists.

**Comment by Hwan-seok** [comment]
Oh, the `gesuterDetector` is just inserted because you asked me if another gesture works

**Comment by suragch** [comment]
I see. I didn't mean to add another gesture recognizer. I meant to add a normal button and see if that received the tap event.

**Comment by Hwan-seok** [comment]
Is it different between gestureDetector and the normal button? I really didn't know that.. Let me try it.

**Comment by Hwan-seok** [comment]
I added two types of buttons.
One is for behind the progress bar.
The other is far apart from it.
Former one does not recog the tap But the other tap works fine.
You can check it on my reproduction code.

**Comment by Hwan-seok** [comment]
@suragch 
I found why this behavior occurring but do not know the solution yet.

When `PageView` with `itemCount = 1`, the  `HorizontalDragGestureRecognizer` calls as follows even just "tap" not "drag"
1. onDown
2. onStart
3. onUpdate
4. onEnd

But with `itemCount > 2` same one calls only `onDown` when "tap" and calls rest of it after "drag"

Is this the flutter internal bug? or expected behavior?
should I leave the issue on flutter?

**Comment by suragch** [comment]
Sorry for the delay in replying. 

I wonder if the `HorizontalDragGestureRecognizer` is conflicting with the `PageView` gesture recognizer. I'm not really sure what the solution is.

**Comment by Hwan-seok** [comment]
I investigated and studied gestures since this issue came out, I might think the `eager gesture recognizer`'s approach is the key solution.
I will submit the pr very soon.

**Comment by AhmadFalahian** [comment]
> I investigated and studied gestures since this issue came out,

Hello my friend
Were you able to find a solution to this problem? I got involved in this problem like you, maybe you can share the solution with me

**Comment by HosseinAsadi** [comment]
> Were you able to find a solution to this problem? I got involved in this problem like you, maybe you can share the solution with me

this issue seems to be solved with this commit 

[https://github.com/suragch/audio_video_progress_bar/pull/29/commits/26a48f9b7f76e821c2a7250cdb78f1aa2fc3995b](url)

but pull request is not merged!

**Comment by Hwan-seok** [comment]
@AhmadFalahian I solved and submitted PR but as @HosseinAsadi mentioned it did not merge.

I understand the author does not accept it because somewhere it could be the breaking change and this issue was reported from only me. 

Use the following forked version until the author accepts it.

```yaml

  audio_video_progress_bar:
    git:
      url: https://github.com/Hwan-seok/audio_video_progress_bar
      ref: 26a48f9b7f76e821c2a7250cdb78f1aa2fc3995b
```
