### ISSUE TITLE
Should we drop `0` padding on time labels less than 10 minutes?

### ISSUE THREAD

**Issue by suragch** [suragch/audio_video_progress_bar#25]
This would change the left and right time labels from this:

```
00:00
03:27
```

to this:

```
0:00
3:27
```

Zero padding for minutes would remain unaffected for hours greater than 0:

```
1:00:00
1:03:27
```

This is related to PR #24.

Since this will affect everyone's UI, please leave a comment here regarding your opinion.

**Comment by giga10** [comment]
`Full support on this one. 😁 

Just to add on your comment from above. 

PR #24 also changes left time label for hours greater than 0 from this:

```
0:08:57
```

to this: 

```
8:57
```

**Comment by suragch** [comment]
> PR #24 would change the left and right time labels for hours greater than 1 from this:
> 
> ```
> 0:00:00
> 1:25:16
> ```

@giga10 Actually, the original version already didn't include `0` hours.

**Comment by giga10** [comment]
@suragch Hm. Latest version: 

![Screenshot_20210924-072400~2.png](https://user-images.githubusercontent.com/80179318/134622975-09b7bf7d-3083-472e-bc46-0db3755b48b9.png)

**Comment by suragch** [comment]
@giga10 My mistake! Thank you for correcting me.

**Comment by suragch** [comment]
This is updated in release 0.10.0.
