### ISSUE TITLE
[Proposal] Add progress bar radius property

### ISSUE THREAD

**Issue by navaronbracke** [suragch/audio_video_progress_bar#28]
When the stroke cap is `StrokeCap.round`, the progress bar is painted with a fixed radius that is half the bar height.

Allow overriding the default by adding a new property `double? progressBarRadius`,
which defaults to `barHeight / 2` if null.

**Comment by suragch** [comment]
Currently the stroke cap maps directly to the `Paint` stroke cap for drawing a line. There isn't a radius option with that that I'm aware of. This could be changed by painting a rectangle with rounded corners. Currently I don't have a plan to do that, so I would recommend you just copy the source code to your project and modify the `_drawBar` method to meet your needs.
