### ISSUE TITLE
time format is wrong

### ISSUE THREAD

**Issue by wtjperi2003** [suragch/audio_video_progress_bar#30]
look at picture. progres time should be 05:22. total time should be 01:58:56.
![微信截图_20211215092541](https://user-images.githubusercontent.com/10322892/146105730-207c8b04-7303-4c76-86d9-47f5cb629184.png)

**Comment by suragch** [comment]
This was changed in version 0.10.0 (#25). You like the left padded zeros?

**Comment by wtjperi2003** [comment]
> This was changed in version 0.10.0 (#25). You like the left padded zeros?

Can you change it to configurable？

**Comment by suragch** [comment]
I don't think I'll add configuration for this, but you can just copy the source code to your project. (See the [0.9.0 release](https://github.com/suragch/audio_video_progress_bar/releases).) It's only a single file.
