### ISSUE TITLE
onTap

### ISSUE THREAD

**Issue by HosseinAsadi** [suragch/audio_video_progress_bar#31]
Can not onTap feature package support? That is, go to the relevant part by clicking, not only by dragging

**Comment by suragch** [comment]
Does onTap not work? I think it works on the example project doesn't it?

**Comment by HosseinAsadi** [comment]
> Does onTap not work? I think it works on the example project doesn't it?

Strangely package example worked! but into our project( like this issue #23 ) not work!

Seems with #29 pull request this issue fixed but it has not been merged!

**Comment by akshg05** [comment]
It works some times when I have not loaded the media but never when the media is loaded.
Need a fix to this.

**Comment by thesensibledev** [comment]
Enhancement Request. Any plans for this?

**Comment by suragch** [comment]
@HosseinAsadi PR #23 was merged in version 0.11.0.
