### ISSUE TITLE
Multiple ProgressBars work as one

### ISSUE THREAD

**Issue by 78Ronin** [suragch/audio_video_progress_bar#32]
How can I make the Progress Bar not be the only one for everyone?

When I play back an audio recording of users, then all existing audio recordings start to display the progress.

https://user-images.githubusercontent.com/69910009/146882878-be9b32bf-ab72-4739-9a49-8937617118b2.mp4

**Comment by suragch** [comment]
This appears to be an issue with your state management. The widget itself only shows the data that you provide to it. My guess is that you would need a different state manager instance for each card or you would need to reset the values if a different card was chosen.

**Comment by 78Ronin78** [comment]
In my case, it turned out to be implemented by adding a condition before displaying the ProgressBar:
if a sound is played, then pass to total duration otherwise pass duration(second: 0) to total.

**Comment by suragch** [comment]
I'm closing this issue for now but let me know if there is still a problem with the widget itself.
