### ISSUE TITLE
[Proposal] Custom time label widget

### ISSUE THREAD

**Issue by navaronbracke** [suragch/audio_video_progress_bar#33]
Currently it is only possible to customize the padding / text style / position of the time labels.

We can't add custom widgets as labels (i.e. what if I want a  yellow circular container as a label).

## Proposal
Allow creating custom labels with a builder function. I.e. `tyedef TimeLabelBuilder = Widget Function(Duration);`

**Comment by suragch** [comment]
Right now I'd recommend one of the two following options:

- Copy the source code to your project and modify it to have the label style that you want.
- Turn off the labels with `timeLabelLocation: TimeLabelLocation.none` and use your own widgets.

**Comment by navaronbracke** [comment]
At this point, I am already using option two. Was just wondering if it would be possible.
