### ISSUE TITLE
Progress Bar is not shown

### ISSUE THREAD

**Issue by WolframCrem** [suragch/audio_video_progress_bar#54]
The progress bar is not shown

`Expanded(
                child: Container(
                  color: Colors.white,
                  // color: const Color(0xff181A1E),
                  child: Column(
                    children: [
                      Padding(
                        padding: const EdgeInsets.fromLTRB(20, 30, 20, 0),
                        child: ProgressBar(
                          progress: const Duration(milliseconds: 1000),
                          buffered: const Duration(milliseconds: 2000),
                          total: const Duration(milliseconds: 5000),
                          onSeek: (duration) {
                            print('User selected a new time: $duration');
                          },
                        ),
                      ),
                    ],
                  ),
                ),
              ),`
              
![image](https://user-images.githubusercontent.com/39000530/206874970-b5626a28-b767-40a7-87d4-06bd4aa3586e.png)

Platform IOS
flutter stable channel

**Comment by WolframCrem** [comment]
impeller seems to be the problem causing it, gonna update to see if it works on the beta channel

**Comment by WolframCrem** [comment]
beta channel seems to have it working, maybe add it to the docs for future people.

**Comment by suragch** [comment]
That's weird. I'll have to look more into that. Thank you for the notice.

**Comment by suragch** [comment]
I'm not getting the hidden progress bar when I test this on the iOS simulator running Flutter 3.7. Maybe whatever bug it was with impeller is fixed now. Let me know if you are still seeing an issue.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA
