### ISSUE TITLE
Left round end cap disappears with --enable-impeller on iOS.

### ISSUE THREAD

**Issue by ozbonus** [suragch/audio_video_progress_bar#55]
![endcap](https://user-images.githubusercontent.com/9308425/218661668-d76d49d8-0e13-4fd2-b3f4-6c8826b0c629.png)

When passing `--enable-impeller` and running on real hardware (iPhone X, iOS 16.2) a rounded left end cap will not be rendered, but it will be on the right side. The screen shot above comes from the example app in this repo.

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=IMQdSTlTXjA

**Comment by zeddyyz** [comment]
I face this exact issue. Hoping for a fix quickly!

**Comment by suragch** [comment]
If this is impeller specific, it is a bug with impeller rather than the widget. Do you know if anyone has opened a bug related to this in the Flutter repo?

**Comment by ozbonus** [comment]
Turns out it was just an Impeller issue and a fix will probably make it into a stable release soon (already available in beta). So, problem solved 🎉

https://github.com/flutter/flutter/issues/124176

**Comment by zeddyyz** [comment]
I can confirm that the issue is fixed with Flutter 3.10
