### ISSUE TITLE
The right time label overflows if If it is longer than '0:00'

### ISSUE THREAD

**Issue by buzheng** [suragch/audio_video_progress_bar#60]
The image shows the problem:

![Simulator Screen Shot - iPhone 14 Pro - 2023-08-14 at 23 03 42](https://github.com/suragch/audio_video_progress_bar/assets/2504245/ba95ca7e-4b24-4971-9776-364e7dc54419)

**Comment by suragch** [comment]
Good catch. Thank you posting the image. This should be fixed now in version 2.0.0.
