### ISSUE TITLE
Total duration is doubled in iOS

### ISSUE THREAD

**Issue by vichuer** [suragch/audio_video_progress_bar#74]
In my app I am using audio_video_progress_bar package to show progress and enable seek functionality in the video player.
I am passing the total duration, obtained from my videoplayer controller to ProgressBar widget. It is working fine in Android. But in iOS the progressbar widget shows the total duration as double. For example if the duration is 4:00 then in iOS it will show 8:00.

I will attach my ProgressBar widget code snippet here:  

```bash

 ProgressBar(
   thumbColor: Colors.white,
   baseBarColor: Colors.white24,
   progressBarColor: Colors.white,
   progress: vPosition,
   total: videoPlayerController!.value.duration,
   timeLabelTextStyle:
   const TextStyle(
      color: Colors.white),
      onSeek: (value) {}, )
```

If you want more details feel let me know.

**Comment by Midhunmiyu** [comment]
I'm also facing the same issue as you mentioned...

**Comment by suragch** [comment]
I'd guess that the problem is more likely related to your `videoPlayerController!.value.duration` than it is to `ProgressBar`. You can test it by setting `total: Duration(minutes: 4)` and seeing if it still registers 8:00 on iOS.

**Comment by vichuer** [comment]
@suragch I have tested it by setting `total: Duration(minutes: 4)` . Duration is not doubled now. The issue was with the total duration provided by videoplayer controller. Thanks for the reply..👍🏼
